server:
  port: 9001
grpc:
  server:
    port: 9101
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    hikari:
      schema: bakery
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA}
        format_sql: false
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
    show-sql: true